### ISSUE TITLE
KP with MacBookAir6,1 + Corsair MP510

### ISSUE THREAD

**Issue by xeeee** [kvic-z/SsdPmEnabler#10]
Hi,

Installed a Corsair MP510 on my MacBookAir6,1 and everything seems to work fine.
Idle consumption is around ~0.15A.

Everything is updated, Big Sur 11.5.2 Bootroom 431.140.6.0.0
Installed SsdPmEnabler this morning and the system doesn't boot. Removed SsdPmEnabler and is again fine.

**Comment by kvic-z** [comment]
This is known 'issue' and documented in the FAQ: 

[Why are MacBookAir6,2 and MacBookPro11,1 not supported?](https://github.com/kvic-z/SsdPmEnabler/wiki/FAQ#3-why-are-macbookair62-and-macbookpro111-not-supported)

**Comment by xeeee** [comment]
Oh I didn't know the 6,1 was also included in there.
Do you know if Lilu+NVMEFix works?

**Comment by kvic-z** [comment]
If you can always reproduce the KP, I'm afraid MBA6,1 is on the same boat as MBA6,2

NVMeFix virtually did nothing for my family's MBP12,1 + WD SN550 1TB when we last tried 8 months ago. The minute reduction I saw was completely lost after the very first wake up from sleep. So we decided not bother with it and I haven't looked at it since then. Your mileage may differ. Try and decide yourself.
