### ISSUE TITLE
Contact / REDIR

### ISSUE THREAD

**Issue by tomschlenkhoff** [kvic-z/SsdPmEnabler#6]
Dear Stephen, I'd like to have a quick chat with you concerning REDIR for unbound. Looking to build something like it; if you are willing to release whatever you have, this would be very helpful. Sorry, to contact you this way, but I didn't find any other.

**Comment by kvic-z** [comment]
Dear Tom, 

As you might have expected, I have nothing immediately to offer about REDIR.

What happened around two years ago was that 99% of REDIR code was complete. 90% of a command line helper tool was complete. Then the HDD hosting my VM died, I lost about two-week's code changes of the command line helper. Luckily I had the binary version of the 90%-complete tool for myself. Was prepared to re-write and finish the CLI tool. Then due to many things happened around me, it never got started. 

So currently I'm the only user. It worked miraculously well for the past two years requiring very little attention from me. However, I believe only nerds will appreciate its speed, reliability and elegance. Majority of users won't be able to tell apart from say PiHole or even stock Dnsmasq with scripts. A hundred millisecond second per request vs a few ms per request doesn't matter to most people. A good looking UI on the other hand could attract many eyes.

On the other hand I feel REDIR-like design will be immediately useful to corporates/enterprises or service providers. I never made up my mind to rewrite or release anything because I can't figure out a 'business model' that's self sustainable. Being aware of immediate beneficiaries in corporate side of world, frankly I didn't feel I was generous enough to publish the codes.

I may change my mind or eventually figure out some sort of self-sustainable plan.

Cheers

**Comment by tomschlenkhoff** [comment]
Hey Stephen,

do you mind sending me your contact details besides GitHub issues? This gets old quickly :)
I can totally see us pay your for the project once we understand that our requirements are aligned, and if this counts as "self-sustainable plan” in your eyes.

Have a great weekend!

Tom

**Comment by kvic-z** [comment]
Well Tom, I wish you meant you've got some commercial projects in mind :-)

You could email me at "pcyip-REMOVE-THIS-@-REMOVE-THIS-yahoo.com"

Please discard "-REMOVE-THIS-"
